#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: droot <working directory>"
    exit 1
fi

if [ -z "$(docker images -q dvim)" ]; then
    echo "dvim image not found. Building..."
    docker buildx build -t dvim .
fi

WORKDIR=$1

WORKDIR_PATH=$(realpath $WORKDIR)

WORKDIR_NAME=$(basename $WORKDIR_PATH)

SHARE_NVIM_PATH=".local/share/nvim"
STATE_NVIM_PATH=".local/state/nvim"

mkdir -p ~/.docker-volume/$SHARE_NVIM_PATH
mkdir -p ~/.docker-volume/$STATE_NVIM_PATH

docker run \
	-w /root/$WORKDIR_NAME \
	-v $WORKDIR_PATH:/root/$WORKDIR_NAME \
	-v ~/.docker-volume/$SHARE_NVIM_PATH:/root/$SHARE_NVIM_PATH \
	-v ~/.docker-volume/$STATE_NVIM_PATH:/root/$STATE_NVIM_PATH \
	-it dvim
