#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Usage: droot <working directory>"
	exit 1
fi

if [ -z "$(docker images -q dvim)" ]; then
	echo "dvim image not found. Building..."
	docker buildx build --build-arg USER=$USER -t dvim .
fi

WORKDIR=$1
WORKDIR_PATH=$(realpath $WORKDIR)
WORKDIR_NAME=$(basename $WORKDIR_PATH)

VOLUME=$HOME/.docker-volume

SHARE_NVIM_PATH=".local/share/nvim"
STATE_NVIM_PATH=".local/state/nvim"

mkdir -p $VOLUME/$SHARE_NVIM_PATH
mkdir -p $VOLUME/$STATE_NVIM_PATH

docker run \
	-w $HOME/$WORKDIR_NAME \
	-v $WORKDIR_PATH:$HOME/$WORKDIR_NAME \
	-v $VOLUME/$SHARE_NVIM_PATH:$HOME/$SHARE_NVIM_PATH \
	-v $VOLUME/$STATE_NVIM_PATH:$HOME/$STATE_NVIM_PATH \
	-it dvim
